Cal plot
tidymodels/probably pull request #52
Opened 2022-11-09 21:19 UTC by edgararuiz

Adds 3 calibration plots: breaks (bins), logistic (gam) and sliding window.  They have the corresponding table functions.  They also support `data.frame`, and `tune_results` objects.

2022-11-09 23:22 UTC, topepo requested changes
Looks good overall. 

The main thing is to figure out how to deal with multiple submodels when someone passes `tune_grid()` results to the function.

2022-11-09 23:22 UTC, topepo commented on R/cal-binary.R
> +#' @param include_rug Flag that indicates if the Rug layer is to be included.
Mention what that is and that events are shown on what side of the plot.

2022-11-09 23:22 UTC, topepo commented on R/cal-binary.R
> +  rs <- tune::collect_predictions(.data, summarize = TRUE)
I will add a function later to check these results. We ned to make sure we give them a good error message when they did not use `save_pred = TRUE`. There is also some things related to racing methods that I'll need to check for.

2022-11-09 23:24 UTC, topepo commented on R/cal-binary.R
> +    tune::coord_obs_pred() +
Let's use `lims(x = 0:1. y = 0:1)` instead of `coord_obs_pred()`. This will force the whole scale.

2022-11-09 23:44 UTC, edgararuiz commented on R/cal-binary.R
> +      title = "Calibration Plot",
Ok, should I also remove the subtitle?

2022-11-09 23:47 UTC, edgararuiz commented on R/cal-binary.R
> +                                     window_size = round(nrow(.data) / 10),
Just to confirm, this means that we'll make `window_size` a percentage argument?

2022-11-11 21:11 UTC, edgararuiz commented on R/cal-binary.R
> +  truth <- enquo(truth)
`process_level()` performs validation of `event_level`, do it need to do something more?

2022-11-11 21:14 UTC, edgararuiz commented on R/cal-binary.R
> +#' functions: [cal_binary_table_breaks()], [cal_binary_table_logistic()], and
I'm sorry, I don't understand what the required action is here

2022-11-11 21:34 UTC, topepo commented on R/cal-binary.R
> +  truth <- enquo(truth)
No, that's fine.

2022-11-11 21:36 UTC, topepo commented on R/cal-binary.R
> +#' functions: [cal_binary_table_breaks()], [cal_binary_table_logistic()], and
We might not want these underlying computational functions (e.g. `cal_binary_table_breaks()`)  to be completely exposed to users. If you mark them as internal, they don't show up in the help listings (but still have help packages). A dot prefix is how we usually denote developer facing functions (even if they are exported).

2022-11-13 22:26 UTC, topepo commented
I made some aesthetic changes in the code, most notably to get rid of "binary" in the title (see 965f8d4). 

I added a code comments about test failures on my local machine. 

We may want to save the `tune_grid()` results as an RData object. We can worry about that later since we may need more of them. 

One last question... does the windowed code capture all of the data? When I look at the results of 

``` r
library(probably)
#> 
#> Attaching package: 'probably'
#> The following objects are masked from 'package:base':
#> 
#>     as.factor, as.ordered

cal_plot_windowed(
  segment_logistic,
  Class,
  .pred_good
)
```

![](https://i.imgur.com/SxPNt8O.png)

<sup>Created on 2022-11-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The right-hand side of the line doesn't get near values of 1 on the x-axis (it does get near zero on the left-hand side). Are we getting all the data at the ends?

2022-11-13 22:28 UTC, topepo commented on tests/testthat/test-cal-binary.R
> +  expect_equal(sd(x10$predicted_midpoint), 0.3063903, tolerance = 0.000001)
Locally, on my intel iMac, I get a lot of errors that look to be related to tolerance. I've set the tolerance as low as 0.01 and still get them though. 

```
ℹ Loading probably
[ FAIL 5 | WARN 0 | SKIP 0 | PASS 20 ]

── Failure (test-cal-binary.R:18): Binary breaks functions work ────────────────
sd(x12$predicted_midpoint) (`actual`) not equal to 0.2982188 (`expected`).

  `actual`: 0.293
`expected`: 0.298

── Failure (test-cal-binary.R:43): Binary logistic functions work ──────────────
sd(x22$prob) (`actual`) not equal to 0.2784706 (`expected`).

  `actual`: 0.27
`expected`: 0.28

── Failure (test-cal-binary.R:44): Binary logistic functions work ──────────────
mean(x22$prob) (`actual`) not equal to 0.4765672 (`expected`).

  `actual`: 0.50
`expected`: 0.48

── Failure (test-cal-binary.R:80): Binary windowed functions work ──────────────
sd(x32$predicted_midpoint) (`actual`) not equal to 0.3571706 (`expected`).

  `actual`: 0.31
`expected`: 0.36

── Failure (test-cal-binary.R:81): Binary windowed functions work ──────────────
mean(x32$predicted_midpoint) (`actual`) not equal to 0.4374119 (`expected`).

  `actual`: 0.41
`expected`: 0.44
```

2022-11-13 22:42 UTC, topepo commented
Looking through the window code, I see that the steps are defined in terms of the data and not the probability range. Sorry, I probably wasn't explicit enough when I described that. 

I was thinking that the windows walk along the [0,1] range and capture the observed probability estimates that fall in bins (which probably overlap). 

Here's an example of that that would look like: 

``` r
windows_size <- 0.10
step_size    <- 0.05

steps <- seq(0, 1, by = step_size)
lower_cut <- steps - (windows_size / 2)
lower_cut[lower_cut < 0] <- 0
upper_cut <- steps + (windows_size / 2)
upper_cut[upper_cut > 1] <- 1

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)

tibble(
  step = steps,
  lower = lower_cut,
  upper = upper_cut,
  group = seq_along(steps)
) %>% 
  ggplot(aes(x = step, y = group)) + 
  geom_errorbar(aes(xmin = lower, xmax = upper)) +
  theme_bw()
```

![](https://i.imgur.com/USHqWRn.png)

<sup>Created on 2022-11-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-11-15 20:05 UTC, merged